# Generated by Django 5.1.3 on 2024-12-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfood', '0002_recipe_average_rating_alter_recipe_classify_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='classify',
            field=models.CharField(choices=[('snacks', 'Món Ăn Vặt'), ('vegetarian', 'Chay'), ('asian', 'Món Á'), ('european', 'Món Âu'), ('grill', 'Nướng'), ('appetizer', 'Khai Vị'), ('dessert', 'Tráng Miện')], max_length=10),
        ),
    ]
