# Generated by Django 5.1.3 on 2024-12-02 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfood', '0004_classify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='average_rating',
        ),
    ]
