# Generated by Django 5.1.3 on 2024-12-02 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfood', '0006_alter_classify_name_remove_recipe_classify_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='recipe',
            new_name='recipess',
        ),
    ]
