# Generated by Django 5.1.3 on 2024-12-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfood', '0009_remove_recipe_reported_report_recipe_reports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='reports',
        ),
        migrations.AddField(
            model_name='recipe',
            name='reported',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
