# Generated by Django 5.1.3 on 2024-12-03 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfood', '0010_remove_recipe_reports_recipe_reported_delete_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='recipess',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appfood.recipe'),
        ),
    ]
