# Generated by Django 5.1.3 on 2024-12-04 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfood', '0012_user_alter_comment_user_alter_follow_followed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appfood.user'),
        ),
    ]
